# Generated by Django 4.1.13 on 2024-04-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created']},
        ),
    ]
